# Generated by Django 5.2.4 on 2025-07-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_total', models.FloatField(default=0.0)),
                ('acc_notes', models.TextField(blank=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('trans_amount', models.FloatField()),
                ('trans_notes', models.TextField(blank=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
                ('cat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorytype')),
            ],
        ),
    ]
